# Generated by Django 5.1.5 on 2025-06-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
