# Generated by Django 5.1.5 on 2025-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_organizationprofile_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
