# Generated by Django 5.1.5 on 2025-06-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0003_alter_organizationprofile_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
