# Generated by Django 5.1.5 on 2025-07-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0004_organizationprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/deafaultpic1.jpg', null=True, upload_to='org_logos/'),
        ),
    ]
