# Generated by Django 5.1.5 on 2025-07-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0005_alter_organizationprofile_logo'),
        ('authapp', '0008_delete_candidateprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='candidate_profiles/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='authapp.candidate')),
            ],
        ),
    ]
