# Generated by Django 5.1.5 on 2025-07-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0006_candidateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
