# Generated by Django 5.1.5 on 2025-07-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0007_candidateprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationprofile',
            old_name='profile_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='name',
        ),
    ]
