# Generated by Django 5.1.5 on 2025-07-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0008_rename_profile_name_organizationprofile_company_name_and_more'),
        ('authapp', '0008_delete_candidateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_profile', to='authapp.organization'),
        ),
    ]
