# Generated by Django 5.1.5 on 2025-07-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0009_alter_organizationprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationprofile',
            old_name='user',
            new_name='organization',
        ),
    ]
