# Generated by Django 5.1.5 on 2025-07-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0011_alter_candidateprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/defaultpic1.jpg', null=True, upload_to='candidate_profiles/'),
        ),
    ]
