# Generated by Django 5.1.5 on 2025-07-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0012_alter_candidateprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/deafaultpic1.jpg', null=True, upload_to='candidate_profiles/'),
        ),
    ]
