# Generated by Django 5.1.5 on 2025-07-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0013_alter_candidateprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='address',
        ),
    ]
