# Generated by Django 5.1.5 on 2025-07-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0014_remove_organizationprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='email',
        ),
    ]
