# Generated by Django 5.1.5 on 2025-07-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
