# Generated by Django 5.1.5 on 2025-05-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
