# Generated by Django 5.1.5 on 2025-07-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_candidate_candidateprofile_candidateproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
    ]
