# Generated by Django 5.1.5 on 2025-07-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_delete_candidateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateproject',
            name='joining_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
