# Generated by Django 5.1.5 on 2025-07-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_candidateproject_joining_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateproject',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myprojects', to='authapp.candidate'),
        ),
    ]
